---
- name: Generate an HTML report from jinja template
  hosts: dbservers
  gather_facts: true
  vars: 
    #random settings
    csv_path: /tmp
    csv_filename: report.csv
    headers: Server Name,IP Address,CPU Cores,RAM(GB),Environment

  tasks:
  - name: Save CSV headers
    lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true
  
  - name: Build out CSV file
    lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ inventory_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_processor_count }},{{ (ansible_memtotal_mb/1024)|int }},Production"
      create: true
      state: present
    delegate_to: localhost

  - name: Read in CSV to variable
    community.general.read_csv:
      path: "{{ csv_path }}/{{ csv_filename }}"
    register: csv_file
    delegate_to: localhost
    run_once: true
 
#  - name: debug csv_file
#    debug:
#      var: csv_file
#    run_once: true

  - name: generate HTML report
    template:
      src: report_html.j2
      dest: sample_out.html
      mode: 0777
    delegate_to: 127.0.0.1
