
- name: Prepare Report Header
  hosts: dbservers
  gather_facts: true
  become: true
  tasks:
   - name: check RAM and free
     shell: | 
       echo
       for s in  /sys/block/*/queue/scheduler; do disk=$(echo $s | cut -d "/" -f 4); echo -n "   $disk- "; cat $s; done
     register:  oss

   - name: printout
     debug: 
       msg: "{{ oss.stdout }}"

   - name: printout
     debug:
       msg: "{{ oss.stdout_lines }}"
  
