---
- name: check database threads metrics
  tags: check_threads_metrics
  block:
  - name: Check thread cache size
    command: "mysql -ABNe 'select @@thread_cache_size;'"
    register: thread_cache_size
      
  - name: Check threads created counter
    command: "mysql -ABNe 'select variable_value from information_schema.global_status where variable_name = \"threads_created\";'"
    register: threads_created

  - name: Check Thread cache miss rate
    command: "mysql -ABNe 'select round((((select variable_value from information_schema.global_status where variable_name=\"threads_created\")/(select variable_value from information_schema.global_status where variable_name=\"Connections\")) * 100),2);'"
    register: Thread_cache_miss_rate

  - name: Check Thread cache hit rate
    command: "mysql -ABNe 'select 100 - round((((select variable_value from information_schema.global_status where variable_name=\"threads_created\")/(select variable_value from information_schema.global_status where variable_name=\"Connections\")) * 100),2);'"
    register: Thread_cache_hit_rate
  
  - name: create report file and write header
    shell: echo "* Check thread_cache size" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Thread cache size for {{ ansible_hostname }} - {{ thread_cache_size.stdout }} " >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1

  - name: create report file and write header
    shell: echo "* Check thread_created counter" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Threads created for {{ ansible_hostname }} - {{ threads_created.stdout }} threads" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1

  - name: create report file and write header
    shell: echo "* Check Thread cache Miss Rate" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Thread cache Miss Rate for {{ ansible_hostname }} - {{ Thread_cache_miss_rate.stdout }} %" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1

  - name: create report file and write header
    shell: echo "* Check Thread cache Hit Rate" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Thread cache Hit Rate for {{ ansible_hostname }} - {{ Thread_cache_hit_rate.stdout }} %" >> {{ reportdir }}/threads_io_check
    delegate_to: 127.0.0.1

  - name: Save CSV headers
    lineinfile:
      dest: "{{ csv_path }}/{{ thread_cache_csv_filename }}"
      line: "{{ thread_cache_headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true

  - name: Build out CSV file
    lineinfile:
      dest: "{{ csv_path }}/{{ thread_cache_csv_filename }}"
      line: "{{ inventory_hostname }},{{ thread_cache_size.stdout }},{{ threads_created.stdout }},{{ Thread_cache_hit_rate.stdout }},{{ Thread_cache_miss_rate.stdout }}"
      create: true
      state: present
    delegate_to: localhost

  - name: Read in CSV to variable
    community.general.read_csv:
      path: "{{ csv_path }}/{{ thread_cache_csv_filename }}"
    register: thread_csv_file 
    delegate_to: localhost
    run_once: true

  - name: write HTML file
    template:
      src: thread_cache.j2
      dest: threads_cache.html
      mode: 0777
    delegate_to: 127.0.0.1

  - name: echo report directory
    debug: msg="report written to file - {{ reportdir }}/threads_io_check"
