---
- name: check connectio metrics
  tags: check_connection_metrics
  block:
  - name: Check max connections
    command: "mysql -BNe 'select @@max_connections;'"
    register: max_connections

  - name: Check Max_used_connections
    command: "mysql -BNe 'select variable_value from information_schema.global_status where variable_name = \"Max_used_connections\";'"
    register: max_used_connections

  - name: Check Innodb_stats on metadata flag
    command: "mysql -BNe 'select @@innodb_stats_on_metadata';"
    register: innodb_metadata_flag

  - name: create report file and write header
    shell: echo "* Check max connections" >> {{ reportdir }}/connections_check
    register: file_written
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Max connections for {{ ansible_hostname }} - {{ max_connections.stdout }} conns" >> {{ reportdir }}/connections_check
    delegate_to: 127.0.0.1

  - name: create report file and write header
    shell: echo "* Check max connections used counter" >> {{ reportdir }}/connections_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "max used connections for {{ ansible_hostname }} - {{ max_used_connections.stdout }} conns" >> {{ reportdir }}/connections_check
    delegate_to: 127.0.0.1
  
  - name: create report file and write header
    shell: echo "* Check InnoDB stats on metadata flag" >> {{ reportdir }}/connections_check
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "innodb_metadata_flag for {{ ansible_hostname }} - {{ innodb_metadata_flag.stdout }}" >> {{ reportdir }}/connections_check
    delegate_to: 127.0.0.1
