---
- name: check database version
  tags: check_db_version
  block:
  - name: Check_Existing_DB_Service
    script: check_existing_db_service.sh
    register: db_service_check

  - name: Display_DB_Service_Status
    debug: 
      msg: "{{ db_service_check.stdout }}"
    when: db_service_check.stdout | length > 0

  - name: Check DB version
    command: "mysql -BNe 'select @@version;'"
    register: mariadb_version

  - name: create report file and write header
    shell: echo "* Check MariaDB version" >> {{ reportdir }}/dbVersion_check
    register: file_written
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write MariaDB version to file
    shell: echo "version for {{ ansible_hostname }} - {{ mariadb_version.stdout }} " >> {{ reportdir }}/dbVersion_check
    register: file_written
    delegate_to: 127.0.0.1
    when: mariadb_version | length > 0

  - name: echo report directory
    debug: msg="report written to file - {{ reportdir }}/dbVersion_check"
