---
- name: check innodb_buffer_pool size
  tags: innodb_buffer_pool
  block:
  - name: check innodb_buffer_pool size
    command: "mysql -BNe 'select CONVERT(@@innodb_buffer_pool_size /1024/1024, INTEGER);'"
    register: innodb_buffer_pool_size

  - name: create report file and write header
    shell: echo "* Check InnoDB buffer pool size" >> {{ reportdir }}/bufferpool_check
    register: file_written
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "InnoDB buffer pool size for {{ ansible_hostname }} - {{ innodb_buffer_pool_size.stdout }} MB" >> {{ reportdir }}/bufferpool_check
    register: file_written
    delegate_to: 127.0.0.1
    when: innodb_buffer_pool_size

  - name: echo report directory
    debug: msg="report written to file - {{ reportdir }}/bufferpool_check"

