---
- name: check innodb_buffer_pool size
  tags: innodb_buffer_pool
  block:
  - name: check innodb_buffer_pool size
    command: "mysql -ABNe 'select concat(round(((select variable_value from information_schema.global_status where variable_name=\"Created_tmp_disk_tables\")/(select variable_value from information_schema.global_status where variable_name=\"Created_tmp_tables\")),2),\'%\');'"
    register: temp_table_efiiciency

  - name: create report file and write header
    shell: echo "* Check Temporary Table Efficiency" >> {{ reportdir }}/temp_table_check
    register: file_written
    delegate_to: 127.0.0.1
    run_once: true
    when: inventory_hostname == ansible_play_hosts_all[0]

  - name: write report to file
    shell: echo "Temporary Table efficiency for {{ ansible_hostname }} - {{ temp_table_efiiciency.stdout }}" >> {{ reportdir }}/temp_table_check
    register: file_written
    delegate_to: 127.0.0.1
    when: temp_table_efficiency

  - name: echo report directory
    debug: msg="report written to file - {{ reportdir }}/temp_table_check"

